title: Yizhuo Wu(吴懿卓)<br>
       <br>
       Software Engineer # your name (or website title) here
logo: "https://avatars.githubusercontent.com/yizhuowu" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Academics:<br>
  <img src="images/uci.png" width="100" height="100">
  <img src="images/ColumbiaEngineeringLOGO.jpeg" width="160" height="100"><br>
  •M.S. in Computer Science at Columbia University<br>
  •B.S. in Computer Science at University of California, Irvine<br>
  <br>
  Career:<br>
  Actively seeking Software Engineer position starting May, 2022<br>
  <br>
  <a href="https://www.linkedin.com/in/yizhuo-wu-11116712a/">View Yizhuo's LinkedIn Profile</a><br> 
  <a href="https://github.com/YizhuoWu">View Yizhuo's Github Profile</a><br>
  <a href="https://drive.google.com/file/d/1JVfkBP3X5Lxic2kpWuwLmgTtCab8owfI/view?usp=sharing">View Yizhuo's Resume</a>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
